### ISSUE TITLE
modificación

### ISSUE THREAD

**Issue by VCamila** [RamiroRiggeri/desafio-m4#1]
Hola Ramiro, buenas. Quería felicitarte por el desafío final del módulo 4, la verdad muy bien como se ve en los dos formatos de mobile y desktop, me encantó como te quedó. Sólo quiero decirte que vi unos detalles pequeños que deberías ajustar para que te quede centrado el contenido. Ahora te mando capturas para que veas a lo que me refiero con que te queda descentrado. 
En mi opinión y porque recién lo probé, tenés que modificar en el modo desktop la parte sobre ("about-me__description") ya que veo que el width del texto no queda bien dentro del contenedor sino que te queda afuera de este en bajas resoluciones, probá con 80% o 70% yo hice eso y queda mucho mejor. Por otro lado, también tenés que ver en portfolio en el contenedor, los cards quedan afuera del contenedor cuando se prueba con las resoluciones mas bajas, vi que vos pusiste el padding,  sácalo y fijate como te queda e incluso también donde tenés grid-template-column podes probar con porcentajes o sólo con dos FR y no con tres que así se soluciona este problema.
Igual son correcciones mínimas de visual, para mejorar mas que nada la apariencia, pero la verdad muy bien como fuiste trabajando el desafío. Así que te felicito. 

![2022-03-18 (4)](https://user-images.githubusercontent.com/18042275/159081234-cacffb61-b7f0-4841-bb7e-279225e96950.png)
![2022-03-18 (8)](https://user-images.githubusercontent.com/18042275/159081244-06bab8d6-33eb-44f4-a996-3341d84924af.png)

**Comment by RamiroRiggeri** [comment]
Hola Cami, muchas gracias!!
Ahí corregí ambas cosas, el texto de about-me__description en realidad era porque el contenedor padre, about-me__text tenía un width fijo en pixeles, y al achicarlo sobresalía.
En cuanto al portfolio estuve toqueteando un poco las columnas y los tamaños de las imágenes y pude lograr que quede sin navegación horizontal.
